ControllerHelper/ControllerHelper.csproj, ControllerHelper/profiles/RetroArch.json
As title, added RetroArch profile with whitelist (called passthrough in GUI?), removed all added arguments for easier maintenance later.
Also found a duplicate in profile list (Ayaspace listed twice) and sorted the list alphabetically again.
=> Add RetroArch profile, remove duplicate profile, fix alphabetic order.

ControllerHelper/CmdParser.cs, ControllerHelper/Options.cs
steering axis, invert horizontal or vertical axis
=> implement new API profile settings

ControllerHelper/ControllerHelper.Designer.cs, ControllerHelper/ControllerHelper.cs, ControllerHelper/ControllerHelper.csproj, ControllerHelper/ControllerHelper.resx, ControllerHelper/profiles/RetroArch.json, ControllerService/ControllerService.cs, ControllerService/Properties/Settings.Designer.cs, ControllerService/Targets/ViGEmTarget.cs, ControllerService/XInputController.cs, ControllerService/XInputGirometer.cs
Set of commits for the following:
- Prepare width heigh ratio with already functional value for xinputcontroller and remove UMC gyro x factor
- Remove RetroArch profile (back to where we started, pfff)
=> Features and fixes

ControllerHelper/ControllerHelper.cs, ControllerHelper/MouseHook.cs
=> implement OnPowerChange to Helper

ControllerCommon/Utils.cs, ControllerService/Targets/ViGEmTarget.cs, ControllerService/XInputAccelerometer.cs, ControllerService/XInputController.cs, ControllerService/XInputInclinometer.cs
Inclino meter class added with calculations. ViGEmTarget applies user setting.
See TODO @Valkirie comments for what needs to be linked to GUI
I left the accelometer data filter Euro3D in for now, did not check raw data, might be better.
User can define:
- Max angle to interpret
- To the power of scaling, see: http://www.biology.arizona.edu/biomath/tutorials/power/Graphics/power_family.gif
- Deadzone angle
Possible future needed additions:
- Hysteresis angle
=> Inclinometer functionality based on accelerometer gravity vector

ControllerCommon/Utils.cs, ControllerService/Targets/ViGEmTarget.cs
- Moved function to Utils, single function in vigemtarget.
- Renamed variable to C# convention.
- Removed logging.
- Added commentary.
=> Steering code cleanup

ControllerHelperWPF/ControllerHelperWPF.csproj, ControllerHelperWPF/MathConverter.cs, ControllerHelperWPF/Views/Pages/ProfileSettingsMode1.xaml, ControllerHelperWPF/Views/Pages/ProfileSettingsMode1.xaml.cs, ControllerService/Sensors/XInputInclinometer.cs
- Visual Gauge for several options
- Visual line chart for linearity
- Textual improvements
Note, gauge dial currently non functional.
=> Steering settings page improvements

HandheldCompanion/Views/Pages/ProfileSettingsMode0.xaml.cs
Reflect a more intuitive highlight when user performs an aiming motion with the device around Z and X axis (Y axis is steering).
=> GUI Joystick Camera additional settings bar highlight to also include X

HandheldCompanion/Properties/Settings.Designer.cs, HandheldCompanion/Properties/Settings.settings, HandheldCompanion/Views/Pages/SettingsPage.xaml, HandheldCompanion/Views/Pages/SettingsPage.xaml.cs, HandheldCompanion/Views/Windows/MainWindow.xaml.cs
- StartServiceWithCompanion
- HaltServiceWithCompanion
=> implement new settings

ControllerCommon/ProfileManager.cs, HandheldCompanion/Views/Pages/ProfilesPage.xaml.cs
Profile manager will raise the loaded event when all profiles were loaded.
Profiles page will automictically select the currently used profile.
=> improve profile manager behavior

HandheldCompanion/Views/Pages/ProfilesPage.xaml, HandheldCompanion/Views/Pages/ProfilesPage.xaml.cs
migrate from SimpleStackPanel to LayoutPanel to draw buttons on profiles page
=> Migrate to LayoutPanel

ControllerCommon/MadgwickAHRS.cs, ControllerCommon/SensorFusion.cs, ControllerCommon/Utils/InputUtils.cs, ControllerService/DSUServer.cs, ControllerService/Sensors/XInputGirometer.cs, ControllerService/Sensors/XInputSensor.cs, ControllerService/Targets/DualShock4Target.cs, ControllerService/Targets/ViGEmTarget.cs, ControllerService/XInputController.cs, HandheldCompanion/Views/Pages/ProfileSettingsMode0.xaml.cs
Optimizations and cleanup once prototype works. Like:
- Use vectors
- Move time inside Madgwick Class
- Remove loggers
=> Functional MadgwickAHRS

README.md
Moved visuals higher, lots of people or more visually orientated and would recognize the app sooner or possibly be more inclined to give it a try.
=> Proposal for different readme order.

HandheldCompanion/Properties/Settings.Designer.cs, HandheldCompanion/Properties/Settings.settings, HandheldCompanion/Views/Pages/ControllerPage.xaml.cs, HandheldCompanion/Views/Pages/OverlayPage.xaml.cs, HandheldCompanion/Views/Windows/MainWindow.xaml.cs, HandheldCompanion/Views/Windows/Overlay.xaml, HandheldCompanion/Views/Windows/Overlay.xaml.cs
- CPU and memory consumption reduced.
- UI should have a faster loading time.
=> refactor overlay model swap

HandheldCompanion/Views/Pages/SettingsPage.xaml.cs
Break function if same as before AFTER buttons have been enabled.
=> Fix enabling of mounting option buttons

HandheldCompanion/models/Model8BitDoLite2.cs
=> Update 8BitDoLiteColors and rename file properly.

ControllerCommon/Profile.cs, ControllerCommon/Properties/Resource.zh-CN.resx, ControllerCommon/Properties/Resource.zh-Hant.resx, ControllerCommon/Properties/Resources.Designer.cs, ControllerCommon/Properties/Resources.fr.resx, ControllerCommon/Properties/Resources.resx, ControllerCommon/SensorFusion.cs, ControllerCommon/Utils/InputUtils.cs, ControllerService/Targets/ViGEmTarget.cs, HandheldCompanion/Views/Pages/ProfilesPage.xaml.cs, HandheldCompanion/Views/QuickPages/QuickProfilesPage.xaml.cs
Two items:
- Fix for joystick camera motion input device ratio being applied twice
- New algorithm to handle one devices two poses scenarios for clamp shell like devices.
=> Motion input

README.md
Gif animation with VSC View to showcase input (swipe and click)
Remote play with game screenshot
=> Update readme virtual touchpad information

README.md
Info of features, two screenshots.
=> Readme QuickTools addition

ControllerCommon/Utils/ProcessUtils.cs, ControllerCommon/WinAPI.cs, HandheldCompanion/Managers/Classes/InputsHotkey.cs, HandheldCompanion/Managers/Classes/ProcessEx.cs, HandheldCompanion/Managers/EnergyManager.cs, HandheldCompanion/Managers/HotkeysManager.cs, HandheldCompanion/Managers/ProcessManager.cs, HandheldCompanion/Managers/ProfileManager.cs, HandheldCompanion/Properties/Resources.Designer.cs, HandheldCompanion/Properties/Resources.resx, HandheldCompanion/Views/QuickPages/QuickProfilesPage.xaml.cs, HandheldCompanion/Views/QuickPages/QuickSuspenderPage.xaml.cs, HandheldCompanion/Views/Windows/MainWindow.xaml.cs, HandheldCompanion/Views/Windows/OverlayQuickTools.xaml, HandheldCompanion/Views/Windows/OverlayQuickTools.xaml.cs
see: https://devblogs.microsoft.com/performance-diagnostics/introducing-ecoqos/
=> Fixed EcoQos implementation 

ControllerCommon/Devices/AYANEO2.cs
Tested and confirmed working by several Ayaneo 2 owners.
=> Update OEM keys AYA NEO 2

ControllerCommon/Profile.cs, ControllerCommon/Utils/InputUtils.cs, ControllerService/Targets/DualShock4Target.cs, ControllerService/Targets/ViGEmTarget.cs, ControllerService/Targets/Xbox360Target.cs, HandheldCompanion/Properties/Resources.Designer.cs, HandheldCompanion/Properties/Resources.resx, HandheldCompanion/Views/Pages/ProfilesPage.xaml, HandheldCompanion/Views/Pages/ProfilesPage.xaml.cs, HandheldCompanion/Views/QuickPages/QuickProfilesPage.xaml.cs
Could use a review/look over. I'm satisfied, although long term we might want to change the profile gamepad container order a bit.
=> Gamepad modifications

HandheldCompanion/Resources/Playnite.FullscreenApp.json
Apparently these needed to be swapped.
=> Playnite profile use wrapper instead of allow physical access.

HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml.cs, HandheldCompanion/Views/QuickPages/QuickProfilesPage.xaml.cs
- Fixed duplicate calls to settings manager and power manager
- Added slider restrictions to QuickTools profile page
=> Tdp slider boost sustained part2

ControllerCommon/Properties/Resources.de-DE.resx, ControllerService/Properties/Resources.de-DE.resx, HandheldCompanion/App.xaml.cs, HandheldCompanion/Properties/Resources.de-DE.resx, HandheldCompanion/Views/Pages/SettingsPage.xaml.cs
Relating to [this PR](https://github.com/Valkirie/HandheldCompanion/pull/386), there are still formatting issues with `SettingsPage.xaml.cs`. I only created a new `Resources.de-DE.resx` files and edited `App.xaml.cs`. As soon as i try to edit `SettingsPage.xaml.cs` i'll get huge formatting issues (tested with windows and Linux, terminal and Visual Studio). FOr example, VS looks like this
```ps
PS [...]\HandheldCompanion\HandheldCompanion\Views\Pages> git commit -m "add cB_Language.Items"
[main 669ee5a] add cB_Language.Items
1 file changed, 247 insertions(+), 246 deletions(-)
```
_Edit: Still one day later i'm quite confused about the formatting as the original file is not CRLF nor LF._
I can't get around it, so I'll leave it at this point. So far, it's just a one-liner in …
=>  Create german translation (de-DE)

HandheldCompanion/Actions/MouseActions.cs, HandheldCompanion/Controls/Layout/LayoutTemplate.xaml.cs, HandheldCompanion/Controls/Mapping/AxisMapping.xaml
- Fixed typo
- Reduced sensitivity, makes usable range 21-50
- Default sensitivity for templates starts at 25
=> Improve scroll sensitivity for remapper. #420

ControllerCommon/Controllers/ControllerState.cs, HandheldCompanion/Actions/MouseActions.cs, HandheldCompanion/Controls/Mapping/AxisMapping.xaml, HandheldCompanion/Controls/Mapping/AxisMapping.xaml.cs
- Various cleanups in AxisMapping
- Configurable deadzone implementation for joystick to mouse axis
=> Changes to AxisMapping / MouseAction

HandheldCompanion/Managers/ProfileManager.cs
This way all the profiles, whether they've been loaded and updated or newly
created ones will have latest version when written.
=>  Update Version on serializing profiles

ControllerCommon/Profile.cs, ControllerCommon/Utils/InputUtils.cs, HandheldCompanion/Managers/ProfileManager.cs, HandheldCompanion/Views/Pages/Profiles/SettingsMode0.xaml.cs
Makes for much shorter profiles.
Fixes #478
=> Convert MotionSensivityArray to a SortedDictionary

HandheldCompanion/Managers/ProfileManager.cs, HandheldCompanion/Views/Pages/ProfilesPage.xaml.cs, HandheldCompanion/Views/QuickPages/QuickProfilesPage.xaml.cs
Use the same key as profiles dictionary in ProfileManager (name).
Fixes #477
=> Disallow duplicate entries in the Profile list combo box

HandheldCompanion/Simulators/KeyboardSimulator.cs
=> Wrap InputSimulator.Keyboard in try/catch

HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml, HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml.cs
Available values are: quarter, half, full
=> Define framelimit values based on current screen refresh rate

ControllerCommon/Actions/IActions.cs, HandheldCompanion/Actions/EmptyActions.cs, HandheldCompanion/Controls/Mapping/AxisMapping.xaml, HandheldCompanion/Controls/Mapping/AxisMapping.xaml.cs, HandheldCompanion/Controls/Mapping/ButtonMapping.xaml, HandheldCompanion/Controls/Mapping/ButtonMapping.xaml.cs, HandheldCompanion/Controls/Mapping/TriggerMapping.xaml, HandheldCompanion/Controls/Mapping/TriggerMapping.xaml.cs, HandheldCompanion/Managers/LayoutManager.cs
- rename None to Disabled in layouts
- make it behave as Disabled, not a Pass-through
- basically the state passed to the controller is created only from mappings, no buttons passed from the physical controller should be passed
Fixes #418
=> "Disabled" instead of "None" in layouts/remapper

HandheldCompanion/Managers/Hotkeys/InputsChord.cs, HandheldCompanion/Managers/Hotkeys/InputsHotkey.cs, HandheldCompanion/Managers/HotkeysManager.cs, HandheldCompanion/Managers/InputsManager.cs, HandheldCompanion/Views/Windows/MainWindow.xaml.cs, HandheldCompanion/Views/Windows/OverlayQuickTools.xaml.cs
Allow for hotkeys to be repeated quickly without having to release all buttons.
=> Improve hotkey support

HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml, HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml.cs
Fix float formatting so it'll limit the number of decimals. No longer will you see "16.66666666666666", Just "16.6".
=> Add 1/3 refresh rate option to fps limiter

ControllerCommon/Devices/AYANEO/AYANEOAIRPlus.cs
Requires UMDF2.0_BMI323_v1.0.1.5_Signed_Win11_22H2
[BoschAccelerometer.zip](https://github.com/Valkirie/HandheldCompanion/files/11418348/BoschAccelerometer.zip)
=> Finalize support for AYANEOAir Plus

ControllerCommon/Devices/AOKZOE/AOKZOEA1.cs, ControllerCommon/Devices/AYANEO/AYANEO2.cs, ControllerCommon/Devices/AYANEO/AYANEOAIR.cs, ControllerCommon/Devices/AYANEO/AYANEOAIRPlus.cs, ControllerCommon/Devices/GPD/GPDWin4.cs, ControllerCommon/Devices/GPD/GPDWinMax2.cs, ControllerCommon/Devices/IDevice.cs, ControllerCommon/Devices/OneXPlayer/OneXPlayerMini.cs, ControllerService/ControllerService.cs, ControllerService/DSUServer.cs, ControllerService/Targets/DualShock4Target.cs, ControllerService/Targets/Xbox360Target.cs, HandheldCompanion/Managers/LayoutManager.cs, HandheldCompanion/Managers/SystemManager.cs, HandheldCompanion/Platforms/HWiNFO.cs
Listen for default audio device changes and always set the default as the current one to control the volume for.
=> Make the volume always control the default output audio device

ControllerCommon/MotherboardInfo.cs
Backport from https://github.com/Valkirie/HandheldCompanion/commit/2a83d2411881474c8337066c377280d80ff8b9d4
=> Don't throw on start

HandheldCompanion/Controllers/NeptuneController.cs, neptune-hidapi.net/NeptuneController.cs
Ticks instead of Random.
Pass the task from ReportAsync instead of a new one.
=> Some minor changes around SetHaptic2

HandheldCompanion/PowerProfile.cs
Putting these here for possible future use.
=> Add GUIDs for max CPU frequency and min/max cores settings

HandheldCompanion/Properties/Resources.Designer.cs, HandheldCompanion/Properties/Resources.resx, HandheldCompanion/Views/Pages/SettingsPage.xaml, HandheldCompanion/Views/Pages/SettingsPage.xaml.cs
- Application is now capable to listen to OS theme changes : Accent color, Dark/Light.
- Application theme setting now has three settings: Use system, Light, Dark
=> Implement System Theme Awareness

ControllerCommon/Devices/ASUS/ROGAlly.cs, ControllerCommon/Devices/IDevice.cs, ControllerCommon/LegacyDevcon.cs, ControllerService/ControllerService.cs, HandheldCompanion/Properties/Resources.Designer.cs, HandheldCompanion/Properties/Resources.resx
- Fix gyro behavior on system start.
- Fix front buttons behavior on system resume.
=> Improve gyro support on Rog Ally, AYANEO Air Plus

ControllerCommon/DeviceHelper.cs, ControllerCommon/Devices/ASUS/ROGAlly.cs, ControllerCommon/Devices/IDevice.cs, ControllerCommon/Managers/DeviceManager.cs, ControllerService/ControllerService.cs, HandheldCompanion/Managers/ControllerManager.cs, HandheldCompanion/Views/Windows/MainWindow.xaml.cs
fixed by checking hid status before connecting. #642
=> Rog OEM keys not working on wake up

ControllerCommon/DeviceHelper.cs, HandheldCompanion/Managers/GamepadFocusManager.cs
Fix crash when changing resolution using gamepad. It seems focus is lost during resolution change.
=> fix crash when changing resolution using gamepad.

ControllerService.sln, HandheldCompanion/Properties/Resources.Designer.cs, HandheldCompanion/Properties/Resources.resx, HandheldCompanion/Views/Pages/AboutPage.xaml, HandheldCompanion/Views/Pages/ControllerPage.xaml, HandheldCompanion/Views/Pages/LayoutPage.xaml, HandheldCompanion/Views/Pages/OverlayPage.xaml, HandheldCompanion/Views/Pages/ProfilesPage.xaml, HandheldCompanion/Views/Pages/SettingsPage.xaml
Another update, still not done though. Can be merged, runs, no flaws.
=> Localization update
