Valkirie/HandheldCompanion

- ControllerCommon/ProfileManager.cs
Fixed the issue of a profile name not matching the .exe RetroArch retroarch.
Made the profile dictionary ContainsKey case insenstive through constructor.
From stack overflow: https://stackoverflow.com/questions/13988643/case-insensitive-dictionary-with-string-key-type-in-c-sharp
> Make profile name evaluation case insensitive through constructor

- ControllerService/ControllerService.cs
disconnecting and reconnecting the virtual controller seams to crash Windows 11 on sleep and resume
> prevent crash on system resume

- ControllerCommon/Devices/OneXPlayerMiniAMD.cs
Figured it out with an owner of a device that the keyboard button was not working, tool output:
> Fix OneXPlayer Mini AMD Keyboard key combination

- HandheldCompanion/Views/Pages/OverlayPage.xaml
Slider goes from 0.01 to 0.25, but tooltip only showed rounded 0.1 and 0.2
> AutoToolTip Precision Improvement

- HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml.cs
- HandheldCompanion/Views/QuickPages/QuickProfilesPage.xaml.cs
Call Boost before Sustained, prevents boost first being set the same as sustained and then again being +1d.
> Hotkey TDP + fix for #373

- HandheldCompanion/Actions/MouseActions.cs
- HandheldCompanion/Controls/Layout/LayoutTemplate.xaml.cs
- HandheldCompanion/Views/Pages/LayoutPage.xaml
Proper deadzone application. Minimal deflection over the deadzone results in minimal movement. This way even on highest sensitivity small movement is possible. Sensitivity 100 results in VERY fast movement, but still you can do precise ones.
Don't apply sensitivity twice, use rescale consts to fine tune sensitivity slider. Finetuned for the safe default values of 25.
This greatly improves #420
> Reworked the deadzone and sensitivity of joysticks

- ControllerCommon/Controllers/ControllerState.cs
- HandheldCompanion/Actions/MouseActions.cs
- HandheldCompanion/Controls/Layout/LayoutTemplate.xaml.cs
- HandheldCompanion/Managers/LayoutManager.cs
- HandheldCompanion/Simulators/MouseSimulator.cs
Reworked Mouse TouchPad implementation
And analogous improvements to Mouse Joystick implementation.
This fixes https://github.com/Valkirie/HandheldCompanion/issues/417 and https://github.com/Valkirie/HandheldCompanion/issues/420
Two biggest changes:
- Moved from MoveTo() to MoveBy() implementation. Not because I prefer one or
another but MoveTo() doesn't work with FPP games that center the cursor. Not
sure why and did not manage to make it work despite several tries. The
drawback of MoveBy() is that it's int only and small touchpad movements can be
subpixel, so I've added a code that mitigates that and caches the float
movement that has been left unused after a move cycle. This way very slow
touchpad movement still progresses properly.
Applied this to Joystick as well which visibly …
> Reworked Mouse TouchPad implementation

- HandheldCompanion/Views/Windows/OverlayQuickTools.xaml.cs
Not a global binding or a hotkey. Only works when the window is focused.
Implements #444
> Be able to close the QuickTools windows with an Escape key

- HandheldCompanion/App.config
- HandheldCompanion/Managers/Hotkeys/Hotkey.cs
- HandheldCompanion/Managers/Hotkeys/InputsHotkey.cs
- HandheldCompanion/Managers/HotkeysManager.cs
- HandheldCompanion/Properties/Resources.Designer.cs
- HandheldCompanion/Properties/Settings.Designer.cs
- HandheldCompanion/Properties/Settings.settings
- HandheldCompanion/Views/Pages/SettingsPage.xaml
- HandheldCompanion/Views/Pages/SettingsPage.xaml.cs
- HandheldCompanion/Views/Windows/MainWindow.xaml.cs
By default it's true and has a nice side effect of making the mouse/keyboard work automatically on first HC start after it's installed.
> Add an option to enable desktop profile on application start

- ControllerCommon/Actions/AxisActions.cs
- HandheldCompanion/Actions/MouseActions.cs
- HandheldCompanion/Controls/Mapping/AxisMapping.xaml
- HandheldCompanion/Controls/Mapping/AxisMapping.xaml.cs
- HandheldCompanion/Managers/LayoutManager.cs
This is an implementation of what I mentioned in #456. Implements rotation options for the joysticks, which are useful for the built-in joysticks on handhelds when using the device in different screen orientations (for example, portrait-mode games).
Internally, this implementation makes use of the existing invert axis option and leaves alone the internals of that one, and just adds an additional 90 degree rotation, along with changing the visible option to a slider instead of just toggles. The slider allows selection of 0 (default, no rotation), 90, 180, or 270 degree rotation.
I've also applied a couple Math.Clamp calls in one particular place, which seems to have fixed the issue I reported on #454.
> Implement options for setting rotation on joysticks

- HandheldCompanion/Managers/SystemManager.cs
- HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml
- HandheldCompanion/Views/QuickPages/QuickPerformancePage.xaml.cs
- HandheldCompanion/Views/Windows/MainWindow.xaml.cs
1. Don't send any commands to fan control when it's disabled on start. It's safer that way.
2. Rework conditions in SettingsManager_SettingValueChanged() to only send what's required. Nothing more.
3. Disable Toggle (if enabled) when disabling Override. This way the fan will return to normal when disabling the override during quiet mode work.
4. Remove the Fan Control toggle from the Performance page. It wasn't fully implemented and we have pinnable Quiet Mode in hotkeys.
> Fan control fixes, fixes #461

- HandheldCompanion/Managers/LayoutManager.cs
- HandheldCompanion/Views/Pages/LayoutPage.xaml
- HandheldCompanion/Views/Pages/LayoutPage.xaml.cs
- HandheldCompanion/Views/Pages/ProfilesPage.xaml.cs
- minor cleanups
- remove dead code
- fix for naming the new profile for a game
- fix for overwriting the Desktop profile on HC start
- fix for the "current controller" checkbox
- added a checkbox to export game info with the layout
- finetune the exported profile naming
> Some minor cleanups for the layout exporter functionality

- HandheldCompanion/Controls/Mapping/AxisMapping.xaml
I had this as part of the other pull request, but it was unrelated, so I decided to split it off into its own. Just enables the visibility of the ticks for the axis rotation sliders.
> Display ticks for axis rotation sliders

- ControllerCommon/Profile.cs
- HandheldCompanion/Managers/ProfileManager.cs
- Default profile have layout enabled by default
- New profiles have UMC disabled by default (and layout, this hasn't changed)
> Changed profiles' defaults a little

- HandheldCompanion/Views/Pages/Profiles/SettingsMode1.xaml
There is a dicrepancy between XAML editor and compiled code. Go figure...
https://stackoverflow.com/questions/9122592/elementname-binding-is-failing
> Fix data bindings

- ControllerService/Targets/DualShock4Target.cs
- HandheldCompanion/Managers/LayoutManager.cs
Fix known issues with Dualshock 4 emulation on Steam Deck.
- Gyrometer is now snappy.
- Emulating a 2nd generation DualShock 4 to improve compatibility.
- Properly pass pads clicks and movements to virtual DS4 touch panel.
> Steam deck to Dualshock4 fix

- ControllerCommon/Controllers/IController.cs
- ControllerCommon/Devices/ASUS/ROGAlly.cs
- ControllerCommon/Devices/IDevice.cs
- ControllerCommon/Managers/DeviceManager.cs
- ControllerService/ControllerService.cs
- HandheldCompanion/Managers/ControllerManager.cs
- HandheldCompanion/Views/Pages/ControllerPage.xaml.cs
- HandheldCompanion/Views/Windows/MainWindow.xaml.cs
- Open and Close device on system suspend, resume.
- Use a separated thread on Device.Open() to avoid UI to hang in case we can't pull data out of HidDevice(s).
- Simplify Controller manager XInput slot check logic.
- Prevent crash when calling Device.Close() and device has not yet been opened.
- Allow Controller manager to automatically connect and disconnect controllers when removed or added (if alone).
> Improve device and controller behavior on system resume

- ControllerCommon/Devices/ASUS/ROGAlly.cs
- ControllerCommon/Devices/IDevice.cs
- HandheldCompanion/Views/Windows/MainWindow.xaml.cs
rog ally's oem1 and oem2 key not registering when using emulated ds4 controller in certain apps such as Steam Big Picture.
added a conditional delay based on emulated controller specifically for rog ally's oem1 and oem2 keys. other oem keys don't seem to have the issue.
> oem1 and oem2 key not registering when using emulated ds4 controller

- .github/workflows/publish-hc.yml
Replaces action `mingjun97/file-regex-replace@v1` with a pwsh step.
Github is deprecating the use of Node12 towards the end of summer which this task uses. See: https://github.blog/changelog/2023-06-13-github-actions-all-actions-will-run-on-node16-instead-of-node12-by-default/
Unfortunately the only other available task that I'm aware of is `jacobtomlinson/gha-find-replace` which only works on linux (we're required to use a windows worker due to iscc)
https://github.com/jacobtomlinson/gha-find-replace/issues/33
> Update workflow to use pwsh instead of action for version replace

- HandheldCompanion/Managers/ProcessManager.cs
Add RtkUWP.exe to ignore list, pops up when plugging in headphones on ROG Ally
> Add RtkUWP.exe to ignore list

- HandheldCompanion/Views/Windows/OverlayQuickTools.xaml
- HandheldCompanion/Views/Windows/OverlayQuickTools.xaml.cs
resolves #380 
Shows the current time in the QuickTools window while respecting the current culture (requires restart of HC when changing culture)
> feat(quicktools): show time

- HandheldCompanion/Devices/IDevice.cs
ONE-NETBOOK have released a non-EVA variant of the OneXPlayer 2 Pro. The hardware is identical to the EVA version.
> Add support for OneXPlayer 2 Pro 7840U (non-EVA version).
